// js/state.js

export const state = {
    currentPage: 'splash-page',
    navigationStack: [],
    wheelItems: new Set(),
    currentRestaurantDetails: null,
    detailedRestaurantCache: {},
    isSpinning: false,
    userLocation: null,
    searchRadiusMeters: 500,
    searchCenter: null,
    restaurantData: [], 
    isCategorizing: false,
    categorizationTimerId: null,
    loadingMessageIntervalId: null, // ** [新增] ** 用於追蹤載入訊息計時器
    activeCategory: null,
    focusedCategories: new Set(),
    currentWheelRotation: 0,
    animationFrameId: null,
    filters: {
        openNow: true,
        priceLevel: 0,
        rating: 0,
    },
    isEditingRadius: false,
    isHubExpanded: false,
    isSearchActive: false,
    searchTimeoutId: null,
    isDecidingOnMap: false,
    lastWinner: null,
    isTestMode: false,
    isInitialMapView: true,
};

// ** [修改] ** 擴充 loadingMessages 陣列
export const loadingMessages = [
    "正在召喚美食之神...",
    "派出美食探測無人機...",
    "分析地圖上的卡路里分佈...",
    "詢問附近松鼠的私藏名單...",
    "AI 大廚正在鍋裡翻攪數據...",
    "過濾掉看起來不好吃的選項...",
    "美食雷達掃描中，請稍候...",
    "繪製香噴噴的美食地圖...",
    "正在與外星人交換食譜...",
    "計算麵條的最佳Q彈係數...",
    "把地圖上的地標變成雞腿...",
    "檢查每家餐廳的 WiFi 速度...",
    "為了您，正在跟Google地圖吵架...",
    "派遣鴿子確認店家位置...",
    "下載台灣美食的靈魂..."
];

export const DOMElements = {
    // ... (DOM Elements 保持不變)
    pages: document.querySelectorAll('.page'),
    startBtn: document.getElementById('start-btn'),
    uiTestBtn: document.getElementById('ui-test-btn'),
    locationStatus: document.getElementById('location-status'),
    radiusMap: document.getElementById('radius-map'),
    recenterBtn: document.getElementById('recenter-btn'),
    radiusLabel: document.getElementById('radius-label'),
    confirmRadiusBtn: document.getElementById('confirm-radius-btn'),
    leafletMap: document.getElementById('leaflet-map'),
    categoryList: document.getElementById('category-list'),
    restaurantPreviewList: document.getElementById('restaurant-preview-list'),
    wheelContainer: document.getElementById('wheel-container'),
    spinBtn: document.getElementById('spin-btn'),
    wheelPlaceholder: document.getElementById('wheel-placeholder'),
    backBtns: document.querySelectorAll('.back-btn'),
    wheelCountBadges: document.querySelectorAll('.wheel-count-badge'),
    goToWheelBtn: document.getElementById('go-to-wheel-btn'),
    loadingOverlay: document.getElementById('loading-overlay'),
    loadingText: document.getElementById('loading-text'),
    resultOverlay: document.getElementById('result-overlay'),
    resultText: document.getElementById('result-text'),
    closeResultBtn: document.getElementById('close-result-btn'),
    detailsPage: document.getElementById('details-page'),
    detailsHeaderImage: document.querySelector('.details-header-image'),
    detailsTitle: document.querySelector('.details-title'),
    detailsRating: document.querySelector('.details-rating'),
    detailsPrice: document.querySelector('.details-price'),
    detailsStatus: document.querySelector('.details-status'),
    callBtn: document.getElementById('call-btn'),
    websiteBtn: document.getElementById('website-btn'),
    addToWheelDetailsBtn: document.getElementById('add-to-wheel-details-btn'),
    detailsHoursList: document.querySelector('.details-hours-list'),
    detailsReviewsList: document.querySelector('.details-reviews-list'),
    
    categoriesPage: document.getElementById('categories-page'),
    filterBtn: document.getElementById('filter-btn'),
    resizeRadiusBtn: document.getElementById('resize-radius-btn'),
    returnToCenterBtn: document.getElementById('return-to-center-btn'),
    filterPanel: document.getElementById('filter-panel'),
    closeFilterBtn: document.getElementById('close-filter-btn'),
    openNowToggle: document.getElementById('open-now-toggle'),
    priceFilterButtons: document.querySelector('.filter-buttons[data-filter="priceLevel"]'),
    ratingFilterButtons: document.querySelector('.filter-buttons[data-filter="rating"]'),
    
    pageHeaderCondensed: document.querySelector('.page-header-condensed'),
    mapBottomDrawer: document.querySelector('.map-bottom-drawer'),

    floatingActionHub: document.getElementById('floating-action-hub'),
    hubToggleBtn: document.getElementById('hub-toggle-btn'),
    hubItemList: document.getElementById('hub-item-list'),

    mainFooter: document.getElementById('main-footer'),
    editModeControls: document.getElementById('edit-mode-controls'),
    reSearchBtn: document.getElementById('re-search-btn'),
    cancelEditBtn: document.getElementById('cancel-edit-btn'),
    
    showCandidatesFooterBtn: document.getElementById('show-candidates-footer-btn'),
    candidateListOverlay: document.getElementById('candidate-list-overlay'),
    candidateListContent: document.getElementById('candidate-list-content'),
    closeCandidateListBtn: document.getElementById('close-candidate-list-btn'),
    randomDecisionBtn: document.getElementById('random-decision-btn'),
    
    locationSearchContainer: document.getElementById('location-search-container'),
    locationSearchToggleBtn: document.querySelector('.location-search-toggle-btn'),
    locationSearchInput: document.getElementById('location-search-input'),
    locationSearchResults: document.getElementById('location-search-results'),
    
    showAllBtn: document.getElementById('show-all-btn'),
};